apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3 #Делаем по 3 реплики в каждый узел
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry/myapp:latest # Указывать нужный образ и registry
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            memory: "256Mi"
            cpu: "500m"
            # 0.2 ядра должно хватить для начала и дальнейшей работы, 0.5 - максимум. Память примерно равна 128, но не больше 256
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          failureThreshold: 3
          # приложение требует около 5-10 секунд для инициализации, periodSeconds * failureThreshold должно быть достаточно
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: myapp  
            topologyKey: topology.kubernetes.io/zone  
        # Добавим podAntiAffinity для топологии кластера
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
    # Добавим сервис
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
        # В HPA укажем, что минимальное количество реплик равно 3, а максимальное 5. Целевая загрузка CPU 50% от requests
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: 
  name: myapp-pdb
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: myapp
      # Добавил PDA для отказоустойчивости, выбрал 3 ноды, чтобы не было конфликта с HPA и стартовым количеством реплик